import { Hero } from './hero';

export const HEROES: Hero[] = [
  {
    id: 1,
    name: 'Blue-Eyes Ultimate Dragon',
    type: 'Fiend',
    desc: 'An ultimate dragon with three heads and immense power',
    attack: 95,
    defence: 90,
  },
  {
    id: 2,
    name: 'Dark Magician',
    type: 'Dark',
    desc: 'A powerful sorcerer with mastery over dark magic',
    attack: 88,
    defence: 85,
  },
  {
    id: 3,
    name: 'Red-Eyes Black Dragon',
    type: 'Dark',
    desc: 'A fierce dragon with red scales and burning breath',
    attack: 90,
    defence: 80,
  },
  {
    id: 4,
    name: 'Elemental HERO Neos',
    type: 'Fiend',
    desc: 'A hero with control over elemental forces',
    attack: 85,
    defence: 82,
  },
  {
    id: 5,
    name: 'Dark Magician Girl',
    type: 'Dark',
    desc: 'A skilled sorceress and companion to the Dark Magician',
    attack: 82,
    defence: 78,
  },
  {
    id: 6,
    name: 'Exodia the Forbidden One',
    type: 'Fiend',
    desc: 'A forbidden being comprised of five powerful pieces',
    attack: 100,
    defence: 100,
  },
  {
    id: 7,
    name: 'Black Luster Soldier - Envoy of the Beginning',
    type: 'Fiend',
    desc: 'A powerful warrior with both light and dark attributes',
    attack: 95,
    defence: 85,
  },
  {
    id: 8,
    name: 'Harpie Lady Sisters',
    type: 'Fiend',
    desc: 'Three elegant sisters with the power of the harpies',
    attack: 88,
    defence: 82,
  },
  {
    id: 9,
    name: 'Dark Paladin',
    type: 'Dark',
    desc: 'A fusion of dark spellcasters with dragon-slaying abilities',
    attack: 92,
    defence: 88,
  },
  {
    id: 10,
    name: 'Obelisk the Tormentor',
    type: 'Fiend',
    desc: 'A god-like creature with overwhelming power',
    attack: 100,
    defence: 100,
  },
  // Add more heroes inspired by Yu-Gi-Oh! monsters
];
